language: r
cache: packages

notifications:
  email:
    on_success: change
    on_failure: change

r_packages:
  - drat

before_install:
  - tlmgr install fancyvrb units
  - Rscript -e 'install.packages("nlme", lib="/home/travis/R-bin/lib/R/library/")'

#before_script:
#  - make

after_success:
  - wget https://raw.githubusercontent.com/jr-packages/drat/master/deploy.sh
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy.sh
